[phases.install]
cmds = [
    "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt && pip install --force-reinstall --no-deps opencv-python-headless>=4.8.0"
]
